src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 120)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $owner;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime')]
    private $updatedAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $small_description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSmallDescription(): ?string
    {
        return $this->small_description;
    }

    public function setSmallDescription(string $small_description): self
    {
        $this->small_description = $small_description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <link rel="stylesheet" href="{{ asset("node_modules/bootstrap/dist/css/bootstrap.css") }}">
    <link rel="stylesheet" href="{{ asset("styles.css") }}">
    {% block stylesheets %}
    {% endblock %}

</head>
<body style="padding-bottom: 24px;">
{% include("components/navbar.html.twig") %}
{% block body %}
    <div class="container-fluid mt-lg-5">
        <div class="text-lg-center">
            <h1 class="alert-heading"> Welcome in<span class="text-info"> SociRak</span> !</h1>
        </div>
        <div class="text-lg-start col-8 mx-auto">
            <h3 class="mt-5" style="font-size:24px;margin-left: 14%">
                Here is a view of our latest blogs
            </h3>

        </div>

        <div class="container-lg mx-auto mt-lg-4">
            <div class="col mb-2">
                {% for article in articles %}
                <div class="col-8 mx-auto " style="max-height:500px; overflow: clip">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative my-5">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-primary">World</strong>
                            <h3 class="mb-0">{{ article.title }}</h3>
                            <div class="mb-1 text-muted">{{ article.createdAt | date('d-m-Y') }}</div>
                            <p class="card-text mb-auto">{{ article.smallDescription}}</p>
                            <a href="{{ path('app_article_view',{id:article.id})}}" class="stretched-link">Continue
                                reading</a>
                        </div>
                        <div class="col-auto d-none d-lg-block card-img">
                            <img src="uploads/articles{{ asset(article.image) }}"/>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{{ include("components/messages.html.twig") }}
{% block javascripts %} {% endblock %}
<script src="{{ asset("node_modules/bootstrap/dist/js/bootstrap.js") }}"></script>
</body>
</html>